## Check the installed libraries

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

## Check Numpy Version

In [175]:
np.__version__

'1.21.5'

## Getting the Data

In [176]:
data = pd.read_csv('/media/sf_Shared_Folder/ML_ZoomCamp/Cars_Data.csv')

In [177]:
data

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

## identify the most frequent car manufacturers

In [178]:
data['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

## the number of unique Audi car models

In [179]:
audi_df = data[data['Make'] == 'Audi']

In [180]:
audi_models=audi_df['Model'].value_counts()

In [181]:
len(audi_models.tolist())

34

## columns in the dataset have missing values

In [182]:
C_null=data.columns[data.isna().any()].tolist()
len(C_null)

5

**median value of "Engine Cylinders" column**

In [183]:
print(data['Engine Cylinders'].median())

6.0


**Most frequent value of the Engine Cylinders**

In [184]:
EC_mode=data['Engine Cylinders'].mode()
EC_mode

0    4.0
Name: Engine Cylinders, dtype: float64

In [185]:
data['Engine Cylinders'].isna().sum()

30

**To fill missing values with Mode**

In [186]:
data['Engine Cylinders'] = data['Engine Cylinders'].fillna(value=EC_mode,inplace=False)

**Most frequent value of the Engine Cylinders after filling Missing Values**

In [187]:
print(data['Engine Cylinders'].median())

6.0


**Select lotus Cars**

In [188]:
df_1 = data[data['Make'] == 'Lotus']
df_1

Make      Model  Year                Engine Fuel Type  Engine HP  \
3912  Lotus      Elise  2009     premium unleaded (required)      189.0   
3913  Lotus      Elise  2009     premium unleaded (required)      218.0   
3914  Lotus      Elise  2009     premium unleaded (required)      189.0   
3915  Lotus      Elise  2010     premium unleaded (required)      189.0   
3916  Lotus      Elise  2010     premium unleaded (required)      218.0   
3917  Lotus      Elise  2011     premium unleaded (required)      189.0   
3918  Lotus      Elise  2011     premium unleaded (required)      217.0   
3919  Lotus      Elise  2011     premium unleaded (required)      217.0   
4216  Lotus     Esprit  2002     premium unleaded (required)      350.0   
4217  Lotus     Esprit  2003     premium unleaded (required)      350.0   
4218  Lotus     Esprit  2004     premium unleaded (required)      350.0   
4257  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4258  Lotus  Evora 400  2017     premium unleaded (required)      400.0   
4259  Lotus      Evora  2011     premium unleaded (required)      276.0   
4260  Lotus      Evora  2011     premium unleaded (required)      276.0   
4261  Lotus      Evora  2013     premium unleaded (required)      276.0   
4262  Lotus      Evora  2013     premium unleaded (required)      345.0   
4263  Lotus      Evora  2013     premium unleaded (required)      345.0   
4264  Lotus      Evora  2013     premium unleaded (required)      276.0   
4265  Lotus      Evora  2014     premium unleaded (required)      345.0   
4266  Lotus      Evora  2014     premium unleaded (required)      276.0   
4267  Lotus      Evora  2014     premium unleaded (required)      345.0   
4268  Lotus      Evora  2014     premium unleaded (required)      276.0   
4292  Lotus      Exige  2009  premium unleaded (recommended)      257.0   
4293  Lotus      Exige  2009  premium unleaded (recommended)      240.0   
4294  Lotus      Exige  2010  premium unleaded (recommended)      240.0   
4295  Lotus      Exige  2011  premium unleaded (recommended)      240.0   
4296  Lotus      Exige  2011  premium unleaded (recommended)      257.0   
4297  Lotus      Exige  2011  premium unleaded (recommended)      257.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   
3917               4.0            MANUAL  rear wheel drive              2.0   
3918               4.0            MANUAL  rear wheel drive              2.0   
3919               4.0            MANUAL  rear wheel drive              2.0   
4216               8.0            MANUAL  rear wheel drive              2.0   
4217               8.0            MANUAL  rear wheel drive              2.0   
4218               8.0            MANUAL  rear wheel drive              2.0   
4257               6.0            MANUAL  rear wheel drive              2.0   
4258               6.0            MANUAL  rear wheel drive              2.0   
4259               6.0            MANUAL  rear wheel drive              2.0   
4260               6.0            MANUAL  rear wheel drive              2.0   
4261               6.0            MANUAL  rear wheel drive              2.0   
4262               6.0            MANUAL  rear wheel drive              2.0   
4263               6.0            MANUAL  rear wheel drive              2.0   
4264               6.0            MANUAL  rear wheel drive              2.0   
4265               6.0            MANUAL  rear wheel drive              2.0   
4266               6.0            MANUAL  rear wheel drive              2.0   
4267              

**Select specific columns**

In [189]:
df_2 = df_1[["Engine HP","Engine Cylinders"]]
df_2

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [190]:
df_3=df_2.drop_duplicates()
df_3

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

**Convert df_3 to a Numpy Array**

In [191]:
X=np.array(df_3)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

**Calculate the transpose**

In [192]:
TX=np.transpose(X)
TX

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

**Matrix Matrix Multiplication**

In [193]:
XTX=np.matmul(X,X.T)
XTX


array([[ 35737.,  41218.,  41029.,  66182.,  75624.,  52188.,  65229.,
         48589.,  45376.],
       [ 41218.,  47540.,  47322.,  76332.,  87224.,  60192.,  75234.,
         56042.,  52336.],
       [ 41029.,  47322.,  47105.,  75982.,  86824.,  59916.,  74889.,
         55785.,  52096.],
       [ 66182.,  76332.,  75982., 122564., 140048.,  96648., 120798.,
         89982.,  84032.],
       [ 75624.,  87224.,  86824., 140048., 160036., 110436., 138036.,
        102824.,  96024.],
       [ 52188.,  60192.,  59916.,  96648., 110436.,  76212.,  95256.,
         70956.,  66264.],
       [ 65229.,  75234.,  74889., 120798., 138036.,  95256., 119061.,
         88689.,  82824.],
       [ 48589.,  56042.,  55785.,  89982., 102824.,  70956.,  88689.,
         66065.,  61696.],
       [ 45376.,  52336.,  52096.,  84032.,  96024.,  66264.,  82824.,
         61696.,  57616.]])

**Matrix Inverse**

In [194]:
XTX_i= np.linalg.inv(XTX) 
XTX_i

array([[-2.18898876e+12, -7.56359796e+11,  1.14434644e+11,
         2.00513935e+11, -1.66320285e+11,  1.12310221e+12,
         7.46575013e+10,  1.49042689e+11,  7.33684212e+11],
       [-6.30802035e+12, -2.01259813e+12, -1.47385584e+11,
         2.87241171e+11, -1.66950245e+12,  3.15151096e+12,
         1.00865481e+12,  8.58948729e+11,  3.29857800e+12],
       [-6.46414009e+12, -2.14341265e+12, -7.02956401e+10,
         4.65754129e+11, -1.37820922e+12,  3.11140511e+12,
         9.17353014e+11,  7.26571065e+11,  3.04394570e+12],
       [ 3.85893106e+12,  1.27421825e+12,  6.53010899e+10,
        -2.53373934e+11,  7.49335291e+11, -1.94749457e+12,
        -4.81560399e+11, -4.34397769e+11, -1.73772525e+12],
       [ 2.44914187e+11,  1.01325947e+11, -1.92780781e+10,
        -7.89758704e+10, -7.29029853e+10, -9.29173978e+10,
         5.72378295e+10, -1.22583165e+09, -4.91065269e+09],
       [-1.95915429e+12, -6.73125298e+11, -1.20642014e+11,
         8.20608546e+10, -5.16204964e+11,  1.018132

**Create an array y**

In [195]:
y= np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

**Multiply the XTX_i with TX, and then multiply the result by y**

In [196]:
a=np.matmul(XTX_i,X)
w=np.matmul(y,a)
w

array([  755.6640625 , -1276.59912109])